fix: resolve various parser issues
esxjs/to-esx pull request #7
Opened 2020-08-15 16:02 UTC by irudoy

* set `ecmaVersion` acorn option to `2020` (https://github.com/esxjs/esx/issues/17)
* fix function attributes parsing (https://github.com/esxjs/esx/issues/17)
* fix imported components registration (fix: #2)
* add lockfile

2020-08-17 17:51 UTC, prograhammer commented
@irudoy I tried out this change (just directly added the code in node_modules to-esx) and still see it breaking on optional chaining.

2020-08-17 18:13 UTC, irudoy commented
@prograhammer can you provide stack trace of error thrown with these changes?

2020-08-17 19:21 UTC, prograhammer commented
@irudoy there's no new errors that appear with these changes, I'm just noticing that optional chaining still breaks. See here: https://github.com/esxjs/esx/issues/17

2020-08-17 19:27 UTC, prograhammer commented
@irudoy BTW, I'm able to get through this issue by transpiling (via babel-loader) twice. I do one pass through babel on the optional chaining, etc, then another pass with `babel-plugin-esx-ssr`. However now I'm facing an issue with none of the components registering from esx:

```js
ReferenceError: ESX: FooComponent not found in registered components","stack":"ReferenceError: ESX: 
FooComponent not found in registered components\n    at grow (webpack-
internal:///./node_modules/esx/lib/parse.js:116:13)\n    at parse (webpack-
internal:///./node_modules/esx/lib/parse.js:363:11)\n    at raw (webpack-internal:///./node_modules/esx/index.js:292:24)\n    
at render (webpack-internal:///./node_modules/esx/index.js:350:31)\n 
```

2020-08-17 19:51 UTC, prograhammer commented
@irudoy Update: I think the `ReferenceError: ESX: FooComponent not found in registered components` error my be comiing from `renderToNodeStream`. I tried with`renderToString` and the error went away. I still need to confirm ESX is working though.

2020-08-17 21:05 UTC, prograhammer commented
@irudoy Now I'm transforming `import/exports` to commonjs (`require`). That get's be past the register errors, but now I'm getting `ReferenceError: React is not defined`.

2020-08-18 01:48 UTC, irudoy commented
@prograhammer first of all consider, that esx project isn't stable for now, and I'm also trying to get it to work with my codebase as well 😄 Personally, I'm not using `babel-plugin-esx-ssr` because it has issues, and with `webpack` it's more rational to use a loader to convert the whole module to esx.

Registration issues with imports should be resolved by this PR. Could you create an isolated repro? And for `React is not defined` too. Seems like it's related to your build tool setup.

2020-08-23 14:11 UTC, davidmarkclements commented on .gitignore
> -package-lock.json
we do want to ignore lock files, imo lock files are for applications, not modules

2020-08-23 14:13 UTC, davidmarkclements requested changes
rm lock files (lock files do not belong in modules) 

I think if this causes another part to break, even if that other part is experimental we need to at least isolate the cause and rationalize it (if not fix it) before we can merge this

2020-12-09 10:45 UTC, closed without merging